[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "4173"
VITE_API_URL = "https://backendbalompie-production.up.railway.app/api"
VITE_WHATSAPP_PHONE = "+50246907489"

# Métricas y monitoreo
[monitoring]
enabled = true
metrics = ["cpu", "memory", "network", "disk"]

# Configuración de logs
[logs]
retention = "7d"
level = "info"
